--- 
publication_form_templates: 
  article: 
    fields: 
      - 
        name: sourcetitle
        rule: R
      - 
        name: sourcevolume
        rule: O
      - 
        name: sourceissue
        rule: O
      - 
        name: sourcepages
        rule: O
      - 
        name: issn
        rule: O
      - 
        name: eissn
        rule: O
      - 
        name: article_number
        rule: O
  common: 
    fields: 
      - 
        name: title
        rule: R
      - 
        name: alt_title
        rule: O
      - 
        name: abstract
        rule: O
      - 
        name: pubyear
        rule: R
      - 
        name: publanguage
        rule: R
      - 
        name: category_hsv_local
        rule: R
      - 
        name: url
        rule: O
      - 
        name: extid
        rule: O
      - 
        name: links
        rule: O
      - 
        name: keywords
        rule: O
      - 
        name: project
        rule: O
      - 
        name: pub_notes
        rule: O
      - 
        name: authors
        rule: R
  dissertation: 
    fields: 
      - 
        name: dissdate
        rule: O
      - 
        name: disstime
        rule: na
      - 
        name: disslocation
        rule: na
      - 
        name: dissopponent
        rule: O
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na
  monograph: 
    fields: 
      - 
        name: issn
        rule: O
      - 
        name: eissn
        rule: O
      - 
        name: extent
        rule: O
      - 
        name: publisher
        rule: O
      - 
        name: place
        rule: O
      - 
        name: series
        rule: O
      - 
        name: isbn
        rule: O
  artwork:
    fields:
      -
        name: sourcetitle
        rule: R
      -
        name: artwork_type
        rule: O
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na
publication_types: 
  - 
    code: journal-articles
    content_types: 
      - ref
    form_templates: 
      - common
      - article
  - 
    code: review-articles
    content_types: 
      - ref
    form_templates: 
      - common
      - article
  - 
    code: editorial-letters
    content_types: 
      - vet
    form_templates: 
      - common
      - article
  - 
    code: book-reviews
    content_types: ~
    form_templates: 
      - common
      - article
  - 
    code: magazine-articles
    content_types: 
      - vet
      - pop
    form_templates: 
      - common
      - article
  - 
    code: books
    content_types: 
      - ref
      - vet
      - pop
    form_templates: 
      - common
      - monograph
  - 
    code: book-chapters
    content_types: 
      - ref
      - vet
      - pop
    fields: 
      - 
        name: sourcetitle
        rule: R
    form_templates: 
      - common
      - monograph
  - 
    code: translations
    content_types: 
      - vet
    fields: 
      - 
        name: authors
        rule: na
      - 
        name: editor
        rule: R
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na
    form_templates: 
      - common
      - monograph
  -
    code: doctoral-thesis
    content_types:
      - vet
    form_templates:
      - common
      - monograph
      - dissertation
  -
    code: reports
    content_types: 
      - ref
      - vet
      - pop
    fields:
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na

    form_templates: 
      - common
      - monograph
  -
    code: conference-papers
    content_types: 
      - ref
      - vet
      - pop
    fields: 
      - 
        name: sourcetitle
        rule: R
    form_templates: 
      - common
      - monograph
  - 
    code: conference-contributions
    content_types: 
      - ref
      - vet
      - pop
    fields: 
      - 
        name: sourcetitle
        rule: R
    form_templates: 
      - common
      - monograph
  - 
    code: edited-book
    content_types: 
      - vet
    fields: 
      - 
        name: authors
        rule: na
      - 
        name: editor
        rule: R
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na

    form_templates: 
      - common
      - monograph
  -
    code: report-chapter
    content_types: ~
    fields:
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na


    form_templates:
      - common
      - monograph 
  -
    code: newspaper-article
    content_types: ~
    form_templates:
      - common
      - article
  -
    code: encyclopedia-entry
    content_types: ~
    fields:
      -
        name: sourcetitle
        rule: R
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na
    form_templates:
      - common
      - monograph
  -
    code: licentiate-thesis
    content_types: ~
    form_templates:
      - common
      - monograph
      - dissertation
  -
    code: journal-issue
    content_types: ~
    fields:
      -
        name: authors
        rule: na
      -
        name: editor
        rule: R
    form_templates:
      - common
      - article
  -
    code: poster
    content_types: ~
    fields:
      -
        name: sourcetitle
        rule: R
      -
        name: issn
        rule: O
      -
        name: eissn
        rule: O
    form_templates:
      - common
  -
    code: proceeding
    content_types: ~
    fields: 
      -
        name: authors
        rule: na
      -
        name: editor
        rule: R
      -
        name: extent
        rule: na
    form_templates:
      - common
      - monograph
  -
    code: patent
    content_types: ~
    fields:
      -
        name: url
        rule: na
      -
        name: extid
        rule: na
      -
        name: links
        rule: na
      -
        name: patent_applicant
        rule: O
      -
        name: patent_application_number
        rule: O
      -
        name: patent_application_date
        rule: O
      -
        name: patent_number
        rule: R
      -
        name: patent_date
        rule: R
    form_templates:
      - common
  -
    code: working-paper
    content_types: ~
    fields:
      -
        name: issn
        rule: na
      -
        name: eissn
        rule: na
    form_templates:
      - common
      - monograph
  -
    code: original-creative-work
    content_types: ~
    form_templates:
      - common
      - monography
      - artwork
  -
    code: curated-exhibition
    content_types: ~
    form_templates:
      - common
      - monograph
      - artwork
  -
    code: other
    content_types: ~
    form_templates: 
      - common
      - article
      - monograph
